# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: datagrepper.spec

# add or remove files that should be synced
files_to_sync:
    - datagrepper.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: datagrepper
# downstream (Fedora) RPM package name
downstream_package_name: datagrepper

actions:
    post-upstream-clone: "wget https://src.fedoraproject.org/rpms/datagrepper/raw/rawhide/f/datagrepper.spec -O datagrepper.spec"
    post-upstream-clone: "wget https://src.fedoraproject.org/rpms/datagrepper/raw/rawhide/f/datagrepper-0.9.5-fix-test.patch -O datagrepper-0.9.5-fix-test.patch"
jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-35
      branch: develop
      owner: lenkaseg
      project: datagrepper
