# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: datagrepper.spec

# add or remove files that should be synced
files_to_sync:
    - datagrepper.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: datagrepper
# downstream (Fedora) RPM package name
downstream_package_name: datagrepper

srpm_build_deps:
  - wget

actions:
   create-archive:
        - "poetry build -f sdist"
        - "sh -c 'echo dist/datagrepper-$(poetry version -s).tar.gz'"
   get-current-version:
        - "poetry version -s"
   post-upstream-clone:
       # we need poetry v1.1.7 because of a bug in 1.1.8 where python evaluates incorrectly
       - "sh -c 'wget https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py && python3 install-poetry.py --version 1.1.7'"

jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-35
      owner: lenkaseg
      project: datagrepper
