# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: datagrepper.spec

# add or remove files that should be synced
files_to_sync:
    - datagrepper.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: datagrepper
# downstream (Fedora) RPM package name
downstream_package_name: datagrepper

jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-stable
      branch: develop
      owner: LenkaSeg
      project: datagrepper
